date_control:
  name: 日期控制器
  description: 控制显示的日期，本创建主要为保证卡片使用，日期不会实时返回，如果手动请注意选择今天回退。
  fields:
    action:
      name: 操作
      description: 选择或填写日期控制操作
      required: true
      selector:
        select:
          options:
            - label: "前一天"         
              value: "previous_day"
            - label: "今天"           
              value: "today"
            - label: "下一天"         
              value: "next_day"
            - label: "选择日期"       
              value: "select_date"

    date:
      name: 日期
      description: "仅在选择'选择日期'时勾选并使用此项"
      required: false
      selector:
        date: {}
